### ISSUE TITLE
Track number in playlists

### ISSUE THREAD

**Issue by indierodo** [Sv443/BetterYTM#117]
### Description of the feature:
I would like to have a track number in the playlists.

### Other info / sketches:
Try this userscript:

```
#contents {
  counter-reset: section;
}

ytmusic-responsive-list-item-renderer::before {
  counter-increment: section;
  content: counter(section, decimal-leading-zero);
  font-size: 1.5em;
  font-weight: bold;
  color: #fff;
  margin-right: 20px;
}
```
<img width="435" alt="image" src="https://github.com/user-attachments/assets/8dbdc6f8-2f2a-4050-b82f-2a0d98ad6dfe">

**Comment by Sv443** [comment]
Thanks for the feature request, I like it and it should be relatively easy to implement.

**Comment by indierodo** [comment]
Here's an update on my userstyle, in case you find it useful. It makes it only displayable on the queue and the playlists (it was showing on the quick dial too)

```css
#contents {
  counter-reset: section;
}

ytmusic-playlist-shelf-renderer ytmusic-responsive-list-item-renderer::before {
  counter-increment: section;
  content: counter(section, decimal-leading-zero);
  font-size: 1.5em;
  font-weight: bold;
  color: #fff;
  margin-right: 20px;
}

ytmusic-player-queue {
  counter-reset: section;
}


ytmusic-player-queue-item::before {
  counter-increment: section;
  content: counter(section, decimal-leading-zero);
  font-size: 1.5em;
  font-weight: bold;
  color: #fff;
  margin-right: 20px;
}
```
